using OPLauncher.DTOs;
using CommunityToolkit.Mvvm.ComponentModel;

namespace OPLauncher.Models;

/// <summary>
/// Represents a manually-added server (e.g., localhost, private servers).
/// These servers are not listed on OldPortal.com and are stored locally.
/// </summary>
public partial class ManualServer : ObservableObject
{
    /// <summary>
    /// Gets or sets the unique identifier for this manual server (auto-generated by LiteDB).
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the display name of the server.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the server host (IP address or hostname).
    /// Examples: "127.0.0.1", "192.168.1.50", "myserver.com"
    /// </summary>
    public string Host { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the server port.
    /// Default ACE server port is 9000.
    /// </summary>
    public int Port { get; set; } = 9000;

    /// <summary>
    /// Gets or sets an optional description of the server.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Gets or sets the server type (ACE or GDLE).
    /// Default is ACE.
    /// </summary>
    public ServerType ServerType { get; set; } = ServerType.ACE;

    /// <summary>
    /// Gets or sets when this server was added (UTC).
    /// </summary>
    public DateTime AddedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets or sets when this server was last connected to (UTC).
    /// Null if never connected.
    /// </summary>
    public DateTime? LastConnected { get; set; }

    /// <summary>
    /// Gets or sets whether this server is currently online.
    /// Updated by ServerMonitorService via UDP ping.
    /// </summary>
    [ObservableProperty]
    private bool _isOnline;

    /// <summary>
    /// Gets or sets when the online status was last checked.
    /// </summary>
    [ObservableProperty]
    private DateTime? _lastStatusCheck;

    /// <summary>
    /// Interval in seconds to check server status when server is ONLINE.
    /// Default: 300 seconds (5 minutes) - reduces unnecessary checks for stable servers.
    /// </summary>
    public int StatusOnlineIntervalSeconds { get; set; } = 300;

    /// <summary>
    /// Interval in seconds to check server status when server is OFFLINE.
    /// Default: 15 seconds - faster response to server recovery.
    /// </summary>
    public int StatusOfflineIntervalSeconds { get; set; } = 15;

    /// <summary>
    /// Gets or sets the current player count (from UDP packet).
    /// -1 indicates unknown/not available.
    /// </summary>
    [ObservableProperty]
    private int _playerCount = -1;

    /// <summary>
    /// Gets or sets whether this is a localhost server.
    /// Auto-detected based on host.
    /// </summary>
    public bool IsLocalhost =>
        Host == "127.0.0.1" ||
        Host == "localhost" ||
        Host == "::1";

    /// <summary>
    /// Gets a formatted connection string for display.
    /// Example: "127.0.0.1:9000"
    /// </summary>
    public string ConnectionString => $"{Host}:{Port}";

    /// <summary>
    /// Gets a display name with connection info.
    /// Example: "My Test Server (127.0.0.1:9000)"
    /// </summary>
    public string DisplayName => $"{Name} ({ConnectionString})";

    /// <summary>
    /// Validates this manual server's data.
    /// </summary>
    /// <returns>A list of validation errors. Empty if valid.</returns>
    public List<string> Validate()
    {
        var errors = new List<string>();

        if (string.IsNullOrWhiteSpace(Name))
            errors.Add("Server name is required");

        if (string.IsNullOrWhiteSpace(Host))
            errors.Add("Server host is required");

        if (Port < 1 || Port > 65535)
            errors.Add("Port must be between 1 and 65535");

        // Basic host validation (IP or hostname)
        if (!string.IsNullOrWhiteSpace(Host))
        {
            var isValidHost = System.Net.IPAddress.TryParse(Host, out _) ||
                             IsValidHostname(Host);

            if (!isValidHost)
                errors.Add("Host must be a valid IP address or hostname");
        }

        return errors;
    }

    /// <summary>
    /// Simple hostname validation.
    /// </summary>
    private static bool IsValidHostname(string hostname)
    {
        if (string.IsNullOrWhiteSpace(hostname))
            return false;

        if (hostname.Length > 253)
            return false;

        // Allow localhost
        if (hostname.Equals("localhost", StringComparison.OrdinalIgnoreCase))
            return true;

        // Basic check: contains only valid characters
        return hostname.All(c => char.IsLetterOrDigit(c) || c == '.' || c == '-');
    }

    /// <summary>
    /// Creates a WorldConnectionDto from this manual server for game launching.
    /// </summary>
    /// <returns>A WorldConnectionDto that can be used to launch the game.</returns>
    public WorldConnectionDto ToConnectionInfo()
    {
        return new WorldConnectionDto
        {
            Host = Host,
            Port = Port,
            ServerType = ServerType,
            Name = Name,
            Description = Description
        };
    }

    /// <summary>
    /// Creates a copy of this manual server.
    /// </summary>
    /// <returns>A new ManualServer with copied values.</returns>
    public ManualServer Clone()
    {
        return new ManualServer
        {
            Id = Id,
            Name = Name,
            Host = Host,
            Port = Port,
            Description = Description,
            ServerType = ServerType,
            AddedAt = AddedAt,
            LastConnected = LastConnected
        };
    }
}
